# -*- coding: utf-8 -*-
"""clean_and_eda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b78o9fccvBugcYI8yGm3b1xKEsi29zCU
"""

import pandas as pd
import numpy as np
from pathlib import Path

# Task 1 — Load and inspect
# Load the three CSVs with pd.read_csv. orders.shape must print (180, 9) before any cleaning.

BASE_DIR = Path(__file__).resolve().parents[1]

orders = pd.read_csv(BASE_DIR / "data/orders.csv")
customers = pd.read_csv(BASE_DIR / "data/customers.csv")
products = pd.read_csv(BASE_DIR / "data/products.csv")

print("Orders shape before cleaning:", orders.shape)
print("Customers shape before cleaning:", customers.shape)
print("Products shape before cleaning:", products.shape)

# Task 2 — Standardize payment_method casing
# Apply .str.strip().str.upper() to payment_method. Before the fix, orders['payment_method'].unique() must show 7 distinct raw values (COD, cod, Card, card, CARD, UPI, upi). After the fix, exactly 3 remain, with counts CARD: 70, UPI: 55, COD: 55.

print("Before cleaning unique values:")
print(orders["payment_method"].unique())
print("Before cleaning distinct count:", orders["payment_method"].nunique())

orders["payment_method"] = orders["payment_method"].str.strip().str.upper()

print("\nAfter cleaning distinct count:", orders["payment_method"].nunique())
print("After cleaning counts:")
print(orders["payment_method"].value_counts())

# Task 3 — Remove duplicate orders
# Using .duplicated(subset=[...], keep='first') on the natural key customer_id, product_id, order_date, quantity, discount_pct, payment_method, rating, returned (everything except order_id, which differs on the duplicated rows by design), detect and drop duplicates. Exactly 5 rows must be flagged and dropped; orders_clean.shape must be (175, 9) afterward. Print the 5 dropped order_id values — they must be O0176, O0177, O0178, O0179, O0180.

natural_key = [
    "customer_id", "product_id", "order_date", "quantity",
    "discount_pct", "payment_method", "rating", "returned"
]

duplicate_mask = orders.duplicated(subset=natural_key, keep="first")

print("Duplicate rows flagged:", duplicate_mask.sum())
print("Dropped order_id values:")
print(orders.loc[duplicate_mask, "order_id"].tolist())

orders_clean = orders.drop_duplicates(subset=natural_key, keep="first").copy()

print("orders_clean shape after dropping duplicates:", orders_clean.shape)

# Task 4 — Impute missing values
# discount_pct: fill NaN with 0 (business rule: no promo code applied). 12 rows affected (count this on the deduplicated frame, i.e. after Task 3).
# rating: fill NaN with the median of the non-null ratings on the deduplicated frame. Print the median before imputing — it must be 3.0. 15 rows affected.
# After imputing, orders_clean[['discount_pct','rating']].isnull().sum() must be {'discount_pct': 0, 'rating': 0}.

discount_missing_before = orders_clean["discount_pct"].isna().sum()
rating_missing_before = orders_clean["rating"].isna().sum()
rating_median = orders_clean["rating"].median()

print("Missing discount_pct before imputation:", discount_missing_before)
print("Missing rating before imputation:", rating_missing_before)
print("Rating median before imputation:", rating_median)

orders_clean["discount_pct"] = orders_clean["discount_pct"].fillna(0)
orders_clean["rating"] = orders_clean["rating"].fillna(rating_median)

print("Missing values after imputation:")
print(orders_clean[["discount_pct", "rating"]].isnull().sum().to_dict())

# Task 5 — Merge and reconcile against Part 1
# Merge the cleaned orders with products (on product_id) and customers (on customer_id). Compute order_value = quantity * price * (1 - discount_pct/100) per row. Print the total: it must be 97358.30 across the 175 cleaned rows.
# This is ₹2,501.90 less than Part 1 Report (a)'s raw total of ₹99,860.20. Write a one-paragraph reconciliation note (in the script's print output, not just a comment) that explicitly attributes this exact delta to the 5 duplicate rows removed in Task 3 (their combined order_value is ₹2,501.90 — sum the order_value of the 5 dropped rows independently as a check) — not to the discount/rating imputation, which does not change any order_value total. A note that just says "cleaning changed the numbers" without this specific attribution does not satisfy this task.

orders_merged = (
    orders_clean
    .merge(products, on="product_id", how="left")
    .merge(customers, on="customer_id", how="left")
)

orders_merged["order_value"] = (
    orders_merged["quantity"] * orders_merged["price"] * (1 - orders_merged["discount_pct"] / 100)
)

total_order_value = orders_merged["order_value"].sum()

dropped_orders = orders.loc[duplicate_mask].copy()
dropped_orders["discount_pct"] = dropped_orders["discount_pct"].fillna(0)

dropped_merged = dropped_orders.merge(products, on="product_id", how="left")
dropped_merged["order_value"] = (
    dropped_merged["quantity"] * dropped_merged["price"] * (1 - dropped_merged["discount_pct"] / 100)
)

duplicate_delta = dropped_merged["order_value"].sum()
part1_raw_total = 99860.20
difference = part1_raw_total - total_order_value

print("Merged cleaned rows:", orders_merged.shape[0])
print("Total order_value after cleaning:", round(total_order_value, 2))
print("Dropped duplicate order_ids:", dropped_orders["order_id"].tolist())
print("Combined order_value of dropped duplicates:", round(duplicate_delta, 2))
print("Difference from Part 1 raw total:", round(difference, 2))

print(
    "\nReconciliation note: Part 1 Report (a) used the raw orders total of "
    f"Rs.{part1_raw_total:,.2f}, while the cleaned pandas pipeline total is "
    f"Rs.{total_order_value:,.2f}. The exact delta of Rs.{difference:,.2f} is caused by "
    f"removing the 5 duplicate rows from Task 3 ({', '.join(dropped_orders['order_id'])}), "
    f"whose combined order_value is Rs.{duplicate_delta:,.2f}. This difference is not caused "
    "by discount or rating imputation: filling missing ratings has no effect on order_value, "
    "and filling missing discount_pct with 0 follows the no-promo business rule without "
    "changing the duplicate-removal reconciliation."
)

# Task 6 — IQR outlier detection on quantity
# Compute Q1, Q3, IQR = Q3 - Q1, lower = Q1 - 1.5*IQR, upper = Q3 + 1.5*IQR on the merged frame's quantity column. Expected: Q1 = 1.0, Q3 = 2.0, IQR = 1.0, lower = -0.5, upper = 3.5. Filter rows outside [lower, upper]: exactly 2 rows — O0011 (quantity 25) and O0098 (quantity 30). Do not drop these rows from the dataset; flag them (e.g. an is_outlier boolean column) for Task 9 to use.

Q1 = orders_merged["quantity"].quantile(0.25)
Q3 = orders_merged["quantity"].quantile(0.75)
IQR = Q3 - Q1
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

orders_merged["is_outlier"] = ~orders_merged["quantity"].between(lower, upper)

outlier_rows = orders_merged.loc[
    orders_merged["is_outlier"],
    ["order_id", "quantity"]
]

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower bound:", lower)
print("Upper bound:", upper)
print("Outlier rows count:", orders_merged["is_outlier"].sum())
print(outlier_rows)

# Task 7 — Hypothesis: does COD have a higher return rate?
# State the hypothesis explicitly in your script's output, then verify with groupby('payment_method')['returned'].agg(['count','mean']). Expected return rates (rounded to 1 decimal): CARD: 14.7%, COD: 44.4%, UPI: 18.9%. Label the hypothesis Confirmed.

print("Hypothesis: COD orders have a higher return rate than CARD and UPI orders.")

return_rate_by_payment = orders_merged.groupby("payment_method")["returned"].agg(["count", "mean"])
return_rate_by_payment["return_rate_pct"] = (return_rate_by_payment["mean"] * 100).round(1)

print("\nReturn rate by payment method:")
print(return_rate_by_payment)

cod_rate = return_rate_by_payment.loc["COD", "return_rate_pct"]
other_rates = return_rate_by_payment.drop(index="COD")["return_rate_pct"]

hypothesis_result = "Confirmed" if cod_rate > other_rates.max() else "Not confirmed"

print("\nHypothesis result:", hypothesis_result)

# Task 8 — Multi-level segmentation
# Group by ['payment_method', 'city_tier'], compute return rate per segment. The single highest-risk segment must be identified explicitly in your output: COD + Tier-2 cities at 54.5% (32 Tier-1 COD orders at 37.5%, versus 22 Tier-2 COD orders at 54.5% — the segmentation must show COD risk is not uniform across tiers, mirroring how a single blended rate can hide where the real problem is concentrated).

segment_return_rate = (
    orders_merged
    .groupby(["payment_method", "city_tier"])["returned"]
    .agg(["count", "mean"])
)

segment_return_rate["return_rate_pct"] = (segment_return_rate["mean"] * 100).round(1)

print("Return rate by payment method and city tier:")
print(segment_return_rate)

highest_risk_segment = segment_return_rate["return_rate_pct"].idxmax()
highest_risk_rate = segment_return_rate.loc[highest_risk_segment, "return_rate_pct"]

cod_tier1_count = segment_return_rate.loc[("COD", 1), "count"]
cod_tier1_rate = segment_return_rate.loc[("COD", 1), "return_rate_pct"]

cod_tier2_count = segment_return_rate.loc[("COD", 2), "count"]
cod_tier2_rate = segment_return_rate.loc[("COD", 2), "return_rate_pct"]

print(
    "\nHighest-risk segment:",
    f"{highest_risk_segment[0]} + Tier-{int(highest_risk_segment[1])} cities at {highest_risk_rate}%"
)

print(
    "COD segmentation insight: COD return risk is not uniform across tiers; "
    f"Tier-1 COD orders have a {cod_tier1_rate}% return rate across {cod_tier1_count} orders, while "
    f"Tier-2 COD orders have a {cod_tier2_rate}% return rate across {cod_tier2_count} orders."
)

# Task 9 — Correlation analysis
# Compute the correlation matrix across rating, returned, discount_pct, quantity. State explicitly which taught correlation-strength band (negligible / weak / moderate / strong, using the 0–0.19 / 0.2–0.39 / 0.4–0.69 / 0.7–1.0 bands) every pairwise value falls into. All six pairs must be labeled negligible (|r| < 0.2) — in particular, label the hypothesis "higher discounts reduce returns" Busted (discount_pct vs returned correlation ≈ -0.09).

corr_cols = ["rating", "returned", "discount_pct", "quantity"]
corr_matrix = orders_merged[corr_cols].corr()

print("Correlation matrix:")
print(corr_matrix.round(3))

def correlation_band(r):
    abs_r = abs(r)
    if abs_r < 0.2:
        return "negligible"
    elif abs_r < 0.4:
        return "weak"
    elif abs_r < 0.7:
        return "moderate"
    else:
        return "strong"

print("\nPairwise correlation strength labels:")

for i in range(len(corr_cols)):
    for j in range(i + 1, len(corr_cols)):
        col1 = corr_cols[i]
        col2 = corr_cols[j]
        r = corr_matrix.loc[col1, col2]
        print(f"{col1} vs {col2}: r = {r:.3f}, strength = {correlation_band(r)}")

discount_return_corr = corr_matrix.loc["discount_pct", "returned"]

hypothesis_result = (
    "Confirmed"
    if discount_return_corr <= -0.2
    else "Busted"
)

print(
    "\nHypothesis: higher discounts reduce returns:",
    hypothesis_result,
    f"(discount_pct vs returned correlation = {discount_return_corr:.3f})"
)

# Task 10 — Outlier-corrected time series
# Convert order_date to datetime, extract year-month, compute monthly total order_value two ways: (1) including the two Task 6 outlier orders, and (2) excluding them. Print both series. Expected (1): 2026-01: 29582.10 (highest month), ..., 2026-06: 11615.40. Expected (2), outlier-corrected: 2026-01: 11637.10, 2026-02: 13195.50, 2026-03: 20318.90 (now the true highest month), 2026-04: 9495.30, 2026-05: 13151.10, 2026-06: 11615.40. State explicitly, in your printed output, that January's apparent lead is an artifact of the two bulk orders landing in January (O0011 on 2026-01-28, O0098 on 2026-01-10), and that March is the genuine peak month once they're excluded — this is the whole point of doing Task 6 before Task 10, not after.
orders_merged["order_date"] = pd.to_datetime(orders_merged["order_date"])
orders_merged["year_month"] = orders_merged["order_date"].dt.to_period("M").astype(str)

monthly_with_outliers = (
    orders_merged
    .groupby("year_month")["order_value"]
    .sum()
    .round(2)
)

monthly_without_outliers = (
    orders_merged.loc[~orders_merged["is_outlier"]]
    .groupby("year_month")["order_value"]
    .sum()
    .round(2)
)

outlier_orders = orders_merged.loc[
    orders_merged["is_outlier"],
    ["order_id", "order_date", "quantity", "order_value"]
].copy()

outlier_orders["order_date"] = outlier_orders["order_date"].dt.strftime("%Y-%m-%d")

highest_with_outliers = monthly_with_outliers.idxmax()
highest_without_outliers = monthly_without_outliers.idxmax()

print("Monthly order_value including outliers:")
print(monthly_with_outliers)

print("\nMonthly order_value excluding outliers:")
print(monthly_without_outliers)

print("\nOutlier orders affecting the time series:")
print(outlier_orders)

print(
    "\nTime-series insight:",
    f"{highest_with_outliers} appears to be the highest month when outliers are included, "
    "but this lead is an artifact of the two bulk orders landing in January "
    f"({outlier_orders.iloc[0]['order_id']} on {outlier_orders.iloc[0]['order_date']}, "
    f"{outlier_orders.iloc[1]['order_id']} on {outlier_orders.iloc[1]['order_date']}). "
    f"After excluding the flagged outliers, {highest_without_outliers} is the genuine peak month."
)

# Part 3 export step: write verified Part 2 numbers for the narrator layer.
import json

narrator_dir = BASE_DIR / "narrator"
narrator_dir.mkdir(exist_ok=True)

findings = {
    "cleaned_total_revenue_inr": round(float(total_order_value), 2),
    "raw_total_revenue_inr": round(float(part1_raw_total), 2),
    "duplicate_reconciliation_delta_inr": round(float(duplicate_delta), 2),
    "return_rate_by_payment": {
        method: round(float(return_rate_by_payment.loc[method, "return_rate_pct"]), 1)
        for method in ["COD", "CARD", "UPI"]
    },
    "highest_risk_segment": {
        "payment_method": highest_risk_segment[0],
        "city_tier": int(highest_risk_segment[1]),
        "return_rate_pct": round(float(highest_risk_rate), 1),
    },
    "true_peak_month": {
        "month": highest_without_outliers,
        "revenue_inr": round(float(monthly_without_outliers.loc[highest_without_outliers]), 2),
    },
    "outlier_inflated_month": {
        "month": highest_with_outliers,
        "apparent_revenue_inr": round(float(monthly_with_outliers.loc[highest_with_outliers]), 2),
        "corrected_revenue_inr": round(float(monthly_without_outliers.loc[highest_with_outliers]), 2),
    },
}

with (narrator_dir / "findings.json").open("w", encoding="utf-8") as f:
    json.dump(findings, f, indent=2)
    f.write("\n")

print("\nExported narrator findings to: narrator/findings.json")
