# -*- coding: utf-8 -*-
"""visualize.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LvGECTm0MkTLTinSC6dtgxCgHeRpvvmu
"""

# Task 11 — Two visualizations (analysis/visualize.py)
# Using Matplotlib, save two PNGs to visualizations/:

# return_rate_by_payment.png — a bar chart of return rate by (cleaned) payment_method, descending, with the exact percentage labeled on each bar, and a title that states the finding (e.g. "COD Returns at 44.4% — 3x Card").
# monthly_revenue_trend.png — a line chart of the outlier-corrected monthly revenue from Task 10 (not the outlier-inflated version), with axis labels and a title naming the actual peak month.
# Both scripts must be re-runnable end-to-end (python analysis/clean_and_eda.py then python analysis/visualize.py) and regenerate identical numbers/files from the raw CSVs every time — no manual editing of intermediate output.

import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parents[1]

DATA_DIR = BASE_DIR / "data"
VIZ_DIR = BASE_DIR / "visualizations"
VIZ_DIR.mkdir(exist_ok=True)

orders = pd.read_csv(DATA_DIR / "orders.csv")
customers = pd.read_csv(DATA_DIR / "customers.csv")
products = pd.read_csv(DATA_DIR / "products.csv")

orders.columns = orders.columns.str.strip()
customers.columns = customers.columns.str.strip()
products.columns = products.columns.str.strip()

orders["payment_method"] = orders["payment_method"].str.strip().str.upper()

natural_key = [
    "customer_id", "product_id", "order_date", "quantity",
    "discount_pct", "payment_method", "rating", "returned"
]

orders_clean = orders.drop_duplicates(subset=natural_key, keep="first").copy()

orders_clean["discount_pct"] = orders_clean["discount_pct"].fillna(0)
orders_clean["rating"] = orders_clean["rating"].fillna(orders_clean["rating"].median())

orders_merged = (
    orders_clean
    .merge(products, on="product_id", how="left")
    .merge(customers, on="customer_id", how="left")
)

orders_merged["order_date"] = pd.to_datetime(orders_merged["order_date"])
orders_merged["order_value"] = (
    orders_merged["quantity"] * orders_merged["price"] * (1 - orders_merged["discount_pct"] / 100)
)

Q1 = orders_merged["quantity"].quantile(0.25)
Q3 = orders_merged["quantity"].quantile(0.75)
IQR = Q3 - Q1
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

orders_merged["is_outlier"] = ~orders_merged["quantity"].between(lower, upper)
orders_merged["year_month"] = orders_merged["order_date"].dt.to_period("M").astype(str)

print("Merged rows:", orders_merged.shape[0])
print("Outlier order IDs:")
print(orders_merged.loc[orders_merged["is_outlier"], "order_id"].tolist())

return_rate_by_payment = (
    orders_merged
    .groupby("payment_method")["returned"]
    .mean()
    .mul(100)
    .sort_values(ascending=False)
    .round(1)
)

cod_rate = return_rate_by_payment.loc["COD"]
card_rate = return_rate_by_payment.loc["CARD"]
cod_vs_card = cod_rate / card_rate

print("Return rate by payment method:")
print(return_rate_by_payment)

plt.figure(figsize=(8, 5))
bars = plt.bar(return_rate_by_payment.index, return_rate_by_payment.values)

for bar in bars:
    height = bar.get_height()
    plt.text(
        bar.get_x() + bar.get_width() / 2,
        height,
        f"{height:.1f}%",
        ha="center",
        va="bottom"
    )

plt.title(f"COD Returns at {cod_rate:.1f}% — {cod_vs_card:.1f}x Card")
plt.xlabel("Payment Method")
plt.ylabel("Return Rate (%)")
plt.ylim(0, return_rate_by_payment.max() + 10)
plt.tight_layout()

return_rate_path = VIZ_DIR / "return_rate_by_payment.png"
plt.savefig(return_rate_path, dpi=150)
plt.show()

print("Saved:", return_rate_path)

monthly_revenue_corrected = (
    orders_merged.loc[~orders_merged["is_outlier"]]
    .groupby("year_month")["order_value"]
    .sum()
    .round(2)
)

peak_month = monthly_revenue_corrected.idxmax()
peak_value = monthly_revenue_corrected.max()

print("Outlier-corrected monthly revenue:")
print(monthly_revenue_corrected)

plt.figure(figsize=(9, 5))
plt.plot(
    monthly_revenue_corrected.index,
    monthly_revenue_corrected.values,
    marker="o"
)

for month, value in monthly_revenue_corrected.items():
    plt.text(month, value, f"{value:.2f}", ha="center", va="bottom", fontsize=9)

plt.title(f"Outlier-Corrected Monthly Revenue Trend — Peak: {peak_month}")
plt.xlabel("Month")
plt.ylabel("Revenue")
plt.tight_layout()

monthly_trend_path = VIZ_DIR / "monthly_revenue_trend.png"
plt.savefig(monthly_trend_path, dpi=150)
plt.show()

print("Saved:", monthly_trend_path)
print(f"Actual peak month after excluding outliers: {peak_month} with revenue {peak_value:.2f}")